In [1]:
import pandas as pd
import numpy as np

# Sample sales dataset 
data = {
    "OrderID": range(1, 11),
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "Dave", "Bob", "Eve", "Charlie", "Alice", "Dave"],
    "Region": ["East", "West", "East", "East", "South", "West", "North", "East", "West", "South"],
    "Product": ["Widget", "Gadget", "Widget", "Gizmo", "Widget", "Gadget", "Gizmo", "Gadget", "Widget", "Gizmo"],
    "Quantity": [10, 5, 8, 3, np.nan, 7, 12, 4, 6, 9],
    "Price": [2.5, 15.0, 2.5, 7.0, 2.5, 15.0, 7.0, 15.0, 2.5, 7.0],
}
df = pd.DataFrame(data)
df

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

In [2]:
print("Pandas version:", pd.__version__)
print("Built on top of NumPy version:", np.__version__)

Pandas version: 3.0.3
Built on top of NumPy version: 2.5.1

In [5]:
import pandas as pd

s = pd.Series([100, 200, 300, 400],
              index=["a", "b", "c", "d"],
              name="Sales")

print(s)
print(type(s))
print(s["b"])

a    100
b    200
c    300
d    400
Name: Sales, dtype: int64
<class 'pandas.Series'>
200

In [6]:
print(type(df))
print(df.columns)
print(df.index)
df

<class 'pandas.DataFrame'>
Index(['OrderID', 'Customer', 'Region', 'Product', 'Quantity', 'Price'], dtype='str')
RangeIndex(start=0, stop=10, step=1)

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

In [7]:
# Save DataFrame to CSV
df.to_csv("sales.csv", index=False)

# Read CSV file
df_csv = pd.read_csv("sales.csv")

# Save DataFrame to JSON
df.to_json("sales.json")

# Read JSON file
df_json = pd.read_json("sales.json")

# Show last 5 rows
df_csv.tail()

   OrderID Customer Region Product  Quantity  Price
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

In [8]:
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

First 3 rows:

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5

Last 3 rows:

   OrderID Customer Region Product  Quantity  Price
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   10 non-null     int64
 1   Customer  10 non-null     str
 2   Region    10 non-null     str
 3   Product   10 non-null     str
 4   Quantity  9 non-null      float64
 5   Price     10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 612.0 bytes

Describe:

        OrderID   Quantity      Price
count  10.00000   9.000000  10.000000
mean    5.50000   7.111111   7.600000
std     3.02765   2.934469   5.471136
min     1.00000   3.000000   2.500000
25%     3.25000   5.000000   2.500000
50%     5.50000   7.000000   7.000000
75%     7.75000   9.000000  13.000000
max    10.00000  12.000000  15.000000

Shape (rows, columns): (10, 6)

In [9]:
# Total Quantity by Region
print(df.groupby("Region")["Quantity"].sum())

# Average Price by Product
print(df.groupby("Product")["Price"].mean())

# Multiple calculations by Region
print(df.groupby("Region").agg({
    "Quantity": "sum",
    "Price": "mean",
    "OrderID": "count"
}))

Region
East     25.0
North    12.0
South     9.0
West     18.0
Name: Quantity, dtype: float64
Product
Gadget    15.0
Gizmo      7.0
Widget     2.5
Name: Price, dtype: float64
        Quantity      Price  OrderID
Region
East        25.0   6.750000        4
North       12.0   7.000000        1
South        9.0   4.750000        2
West        18.0  10.833333        3

In [10]:
# Create Pivot Table
pivot = pd.pivot_table(
    df,
    values="Quantity",
    index="Region",
    columns="Product",
    aggfunc="sum"
)

# Show Pivot Table
pivot

Product  Gadget  Gizmo  Widget
Region
East        4.0    3.0    18.0
North       NaN   12.0     NaN
South       NaN    9.0     0.0
West       12.0    NaN     6.0

In [11]:
# Count missing values
print(df.isnull().sum())

# Show rows with missing values
print(df[df.isnull().any(axis=1)])

# Remove rows with missing values
print(df.dropna())

# Fill missing Quantity with average
df_fill = df.copy()
df_fill["Quantity"] = df_fill["Quantity"].fillna(df_fill["Quantity"].mean())

# Show updated DataFrame
print(df_fill)

OrderID     0
Customer    0
Region      0
Product     0
Quantity    1
Price       0
dtype: int64
   OrderID Customer Region Product  Quantity  Price
4        5     Dave  South  Widget       NaN    2.5
   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0
   OrderID Customer Region Product   Quantity  Price
0        1    Alice   East  Widget  10.000000    2.5
1        2      Bob   West  Gadget   5.000000   15.0
2        3  Charlie   East  Widget   8.000000    2.5
3        4    Alice   East   Gizmo   3.000000    7.0
4        5     Dave  South  Widget   7.111111    2.5
5        6      Bob   West  Gadget   7.000000   15.0
6        7      Eve  North   Gizmo  12.000000    7.0
7        8  Charlie   East  Gadget   4.000000   15.0
8        9    Alice   West  Widget   6.000000    2.5
9       10     Dave  South   Gizmo   9.000000    7.0

In [16]:
df_filled = df.copy()
df_filled["Quantity"] = df_filled["Quantity"].fillna(df_filled["Quantity"].mean())

In [17]:
# A second DataFrame with extra customer info, to merge with df
customer_info = pd.DataFrame({
    "Customer": ["Alice", "Bob", "Charlie", "Dave", "Eve"],
    "City": ["New York", "Chicago", "Boston", "Houston", "Miami"],
    "MembershipLevel": ["Gold", "Silver", "Gold", "Bronze", "Silver"]
})

# merge(): SQL-style join on a common column
merged_df = pd.merge(df, customer_info, on="Customer", how="left")
print("merge() result:")
display(merged_df.head())

# join(): join on index (set Customer as index on both first)
joined_df = df.set_index("Customer").join(customer_info.set_index("Customer"), how="left")
print("\njoin() result:")
display(joined_df.head())

# concat(): stack DataFrames together (e.g., two batches of orders)
batch1 = df.iloc[:5]
batch2 = df.iloc[5:]
concatenated_df = pd.concat([batch1, batch2], ignore_index=True)
print("\nconcat() result (recombined batches):")
display(concatenated_df)

merge() result:

   OrderID Customer Region Product  Quantity  Price      City MembershipLevel
0        1    Alice   East  Widget      10.0    2.5  New York            Gold
1        2      Bob   West  Gadget       5.0   15.0   Chicago          Silver
2        3  Charlie   East  Widget       8.0    2.5    Boston            Gold
3        4    Alice   East   Gizmo       3.0    7.0  New York            Gold
4        5     Dave  South  Widget       NaN    2.5   Houston          Bronze

join() result:

          OrderID Region Product  Quantity  Price      City MembershipLevel
Customer
Alice           1   East  Widget      10.0    2.5  New York            Gold
Bob             2   West  Gadget       5.0   15.0   Chicago          Silver
Charlie         3   East  Widget       8.0    2.5    Boston            Gold
Alice           4   East   Gizmo       3.0    7.0  New York            Gold
Dave            5  South  Widget       NaN    2.5   Houston          Bronze

concat() result (recombined batches):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0